### PR TITLE
Safe extractPub

### LINKED ISSUE #4: `extractPub` fail on empty list
Given

```haskell
extractPub :: [ByteString] -> Maybe ByteString
extractPub = lookup "p" . parseTaggedValue . head
```

It could end up with runtime error when pub key list is empty.
Shall we change to a safer implementation like

```haskell
extractPub :: [ByteString] -> Maybe ByteString
extractPub = \case 
  [] -> Nothing
  (x:_) -> lookup "p" (parseTaggedValue x)
```

### PR DESCRIPTION
**Pull request by hw202207**
- return Nothing when domain has no public keys
- also add gitignore file

fixes #4

### CODE REVIEW

**Review by kazu-yamamoto — APPROVED** [review]
LGTM

**Comment by kazu-yamamoto** [comment]
Merged.
Thank you!
I will make a new release if you wish.

**Comment by hw202207** [comment]
Thanks!!

>  I will make a new release if you wish.

That'll be perfect!

**Comment by kazu-yamamoto** [comment]
Released.

**Pull request merged**
